### ISSUE TITLE
grub4dos-0.4.6a: Processing the preset-menu ... hanging

### ISSUE THREAD

**Issue by gatoab** [chenall/grub4dos#189] opened 2019-02-15 11:29 UTC
On an active NTFS partition whose MBR was updated with grubinst_gui.exe (01.01.2008):
- when using the "grldr (23.dec.2018)", the system try to boot and immediately produce the following message: "Processing the preset-menu" and then the system hang.
- when using the "grldr (31.march.2009)", the system boot and without any problem.

I really need to use grldr (23.dec.2018 grub4dos-0.4.6a).
Please thanks for helping.

**Comment by steve6375** [comment] 2019-02-15 11:49
It may be caused by using an old version of grubinst.
Try using grubinst at https://sites.google.com/a/rmprepusb.com/www/documents/rmprepusb-beta-versions/grubinst%20Windows%20binaries.7z
https://github.com/chenall/grubutils/tree/master/grubutils/grubinst

P.S. Instead of reporting issues here - why not report them on reboot.pro to confirm that it really is an issue first?
Also, you need to state what settings you used in grubinst_gui.exe when installing, etc. if you still have a problem.

**Comment by gatoab** [comment] 2019-02-15 14:17
Same problem persist.
Details:
Via the grubinst_gui recommended below, 
File system : autodetect
Partition: whole mbr
Partman: not ticked
Version: 0.4.6a
Verbose input: ticked
Dont search floppy:ticked
Boot file:GRLDR

**Comment by steve6375** [comment] 2019-02-15 14:20
OK, and can you run RMPrepUSB - Drive Info  - 0 and add the .txt file saved from NotePad into here so we can see what partitions you have.
Maybe you can try a variety of 0.4.6a grldr files from different dates and pin down when the change happened? This would help immensely.
Also, have you tried it on a different system or booting it using QEMU or VirtualBox?

**Comment by gatoab** [comment] 2019-02-15 14:55
It’ s not an usb stuff, so rmprepusb seems not useful. The ntfs partition is on an iscsi target on a nas synology ds918+
I begin to pin down...

**Comment by gatoab** [comment] 2019-02-15 15:37
System was booting with Grub4dos-0.4.5c-2012-12-31.7z
After this one system don’t boot 
...running menu commands (hangup means you have a problematic config)... no bootfile!pxe_blksize set to 512

**Comment by steve6375** [comment] 2019-02-15 16:00
OK - so if you use grldr 0.4.5c 2013-11-30 it does not work?
http://grub4dos.chenall.net/categories/0-4-5c/

**Comment by gatoab** [comment] 2019-02-15 16:03
No to old to hold 10GB vhd

**Comment by steve6375** [comment] 2019-02-15 16:08
You said that the 2012 booted OK but 2018 version does not boot
What we are trying to find out is what change caused the 2018 version to not boot.
The problem is that 2018 version will not boot - the problem is nothing to do with vhd files - the issue is that it is not even getting to the grub4dos menu.

**Comment by gatoab** [comment] 2019-02-15 16:16
Ok, 2012 boot.
But in menu.lst I need to —top —mem map a 10GB vhd.
So 2012 boot but its not useful for my final goal.
2018 do not boot but can map what i need.

A+C

**Comment by steve6375** [comment] 2019-02-15 16:18
yes, but all we know is that at some point between 2012 and 2018 the code in grub4dos was changed so that it no longer boots on your NAS system. What we need to find out is WHEN THE CHANGE WAS MADE.
So you need to test different versions of \grldr to find out when it no longer works.

**Comment by gatoab** [comment] 2019-02-15 16:21
As already mentionned System was booting with Grub4dos-0.4.5c-2012-12-31.7z


After this version system don’t boot and display: 
...running menu commands (hangup means you have a problematic config)... no bootfile!pxe_blksize set to 512

A+C

**Comment by steve6375** [comment] 2019-02-15 16:22
The next version after 0.4.5c 2012-12-31 was 2013-11-30
So are you saying that 0.4.5c 2013-11-30 does not boot to the menu?

**Comment by gatoab** [comment] 2019-02-15 16:24
Yes

**Comment by steve6375** [comment] 2019-02-15 16:25
OK and 2013-01-13 also does not boot to menu?

**Comment by gatoab** [comment] 2019-02-15 16:33
Thats right

A+C

**Comment by gatoab** [comment] 2019-02-15 16:43
But to be noted that Just now when trying to boot a new time with 2012 after the no boot with 2013-01-13, the systeme give me also the message:  running menu command ... already mentionned.
!?!

**Comment by gatoab** [comment] 2019-02-15 16:44
So 2012 do not boot anymore...

A+C

**Comment by steve6375** [comment] 2019-02-15 16:46
try old grubinst?

**Comment by gatoab** [comment] 2019-02-15 16:50
I will try and let you know.
But just now after the no boot 2012 the sytem boot with the gldr 2009

**Comment by steve6375** [comment] 2019-02-15 16:53
It sounds like an intermittent issue. It maybe caused by uninitialised memory or chipset registers.
You need to turn off the NAS so memory is unpowered - wait 120 seconds - turn on and try to boot to menu.
Then repeat this 4 times for the same version of grldr (no changes) to see if the results are repeatable.
Then try different grldr version... etc,

**Comment by gatoab** [comment] 2019-02-15 16:53
With old grubinst and 2012 no boot now

**Comment by gatoab** [comment] 2019-02-15 16:55
I have to go now
Will try that asap and keep you informed

**Comment by gatoab** [comment] 2019-02-17 14:46
Hi,

turn off the NAS - wait 120 seconds : DONE
repeat this 4 times for the same version of grldr: DONE, please see below.

I can load menu.lst with the grldr contained in grub4dos-0.4.5c-2012-10-02.7z

With the grldr in grub4dos-0.4.5c-2012-11-17.7z the system can not load the menu.lst
 
Thanks for helping!

**Comment by steve6375** [comment] 2019-02-17 15:11
I cannot see any 'change' info between those two versions.
As no one else has seen this problem, can you think of any reason why booting from the internal hard disk of your NAS system may be any different from any other PC?
Is it just a normal SATA boot disk as hd0? Is it in any RAID configuration? What if you remove the boot disk and try to boot it in another system or in a USB drive enclosure on another system?
Does grldr start to load? Have you tried the S key and the INSERT key just as it boots for safe mode and single step modes? Try with latest version with S key and INSERT key.
Can you try using bootice to modify the internal menu.lst which is in the \grldr.
add commands such as;
find
geometry (hd0)
pause
displaymem
pause
ls (hd0)/
pause

and report back.

**Comment by gatoab** [comment] 2019-02-17 16:18
Bootice grldr save as ansi utf8 ...?

**Comment by steve6375** [comment] 2019-02-17 16:24
yes, thats fine.

**Comment by gatoab** [comment] 2019-02-17 16:30
The synology Nas present the disk via iscsi, a priori usual (hd0,0)
I try another iscsi taget via my imac, the system react with the same error as with synology
With the most recent gldr booticed (added with the lines you recommend and saved ansi) with the synology the system do not load my menu.lst, a priori nor the grldr menu.lst because immediately displaying the ... processing the preset menu ... and hanging forever.

Ps:
Unsecceful use of s and inset key : nothing happen!?!
Please can you detailed the i have to press and when and together or not ...

**Comment by gatoab** [comment] 2019-02-17 16:32
After about 2minutes hanging after “processing...” system display the following string:   (pd)

**Comment by gatoab** [comment] 2019-02-17 16:37
Here is the grldr menu.lst save “ansi” via bootice:
timeout 10
pxe detect
configfile
default 0

title find /menu.lst, /boot/grub/menu.lst, /grub/menu.lst
errorcheck on
find
geometry (hd0)
pause
displaymem
pause
ls (hd0)/
pause
configfile /boot/grub/menu.lst
configfile /grub/menu.lst
if "%@root%"=="(ud)" && calc *0x82A0=*0x82b9&0xff
if "%@root:~1,1%"=="f" && find --set-root --devices=f /menu.lst && configfile /menu.lst
find --set-root --ignore-floppies --ignore-cd /menu.lst && configfile /menu.lst
find --set-root --ignore-floppies --ignore-cd /boot/grub/menu.lst && configfile /boot/grub/menu.lst
find --set-root --ignore-floppies --ignore-cd /grub/menu.lst && configfile /grub/menu.lst
configfile http://b.chenall.net/menu.lst
errorcheck on
commandline

title commandline
commandline

title reboot
reboot

title halt
halt

**Comment by steve6375** [comment] 2019-02-17 16:41
No - bad menu!
The menu should **start** menu with the lines I gave.

If you have trouble booting grub4dos, try pressing the S key a lot just as it loads grub4dos - you should see a 5 seconds countdown and it will use 'safe mode'. Disk accesses will be much slower however. 

INSERT key is same but it runs grub4dos in debug mode (line by line) -may need 2018 grub4dos 0.4.6a for this???

**Comment by gatoab** [comment] 2019-02-17 16:46
Grldr is the 23 dec 2018 one.

Is this ok now:

find
geometry (hd0)
pause
displaymem
pause
ls (hd0)/
pause

pxe detect
configfile
default 0
timeout 10

title find /menu.lst, /boot/grub/menu.lst, /grub/menu.lst
errorcheck on

configfile /boot/grub/menu.lst
configfile /grub/menu.lst
if "%@root%"=="(ud)" && calc *0x82A0=*0x82b9&0xff
if "%@root:~1,1%"=="f" && find --set-root --devices=f /menu.lst && configfile /menu.lst
find --set-root --ignore-floppies --ignore-cd /menu.lst && configfile /menu.lst
find --set-root --ignore-floppies --ignore-cd /boot/grub/menu.lst && configfile /boot/grub/menu.lst
find --set-root --ignore-floppies --ignore-cd /grub/menu.lst && configfile /grub/menu.lst
configfile http://b.chenall.net/menu.lst
errorcheck on
commandline

title commandline
commandline

title reboot
reboot

title halt
halt

**Comment by steve6375** [comment] 2019-02-17 17:04
yes, but should be   ls (hd0,0)/
my mistake!

**Comment by gatoab** [comment] 2019-02-17 17:15
Ok, here we are:

**Comment by steve6375** [comment] 2019-02-17 17:18
where? nothing there?

**Comment by gatoab** [comment] 2019-02-17 17:33
I resend my las message containing several pics print screen

Do you see those pics now?

**Comment by steve6375** [comment] 2019-02-17 17:35
no - you need to go to the Github issues page and paste them in

**Comment by gatoab** [comment] 2019-02-17 17:41
Ok I will try later thanks

**Comment by gatoab** [comment] 2019-02-18 07:25
Hi,
Are the print screens posted on github useful?

**Comment by steve6375** [comment] 2019-02-18 08:57
I cannot see any. You need to go to GitHub site and paste them in.

**Comment by steve6375** [comment] 2019-02-18 09:31
https://github.com/chenall/grub4dos/issues/189#issuecomment-464615771

**Comment by gatoab** [comment] 2019-02-18 10:15
![img_4600](https://user-images.githubusercontent.com/47024076/52943832-4c3d0f80-336e-11e9-91e5-57a5ac6d2d31.jpg)
![img_4600](https://user-images.githubusercontent.com/47024076/52943851-56f7a480-336e-11e9-921a-129552509ed7.jpg)
![img_4601](https://user-images.githubusercontent.com/47024076/52943856-59f29500-336e-11e9-90e2-f77a3c83bf11.jpg)
![img_4602](https://user-images.githubusercontent.com/47024076/52943866-5d861c00-336e-11e9-9730-76f4bd2a8d1d.jpg)
![img_4603](https://user-images.githubusercontent.com/47024076/52943876-637bfd00-336e-11e9-89a3-a04429f84460.jpg)
![img_4604](https://user-images.githubusercontent.com/47024076/52943881-65de5700-336e-11e9-90c8-70edad54de33.jpg)
![img_4605](https://user-images.githubusercontent.com/47024076/52943882-6840b100-336e-11e9-89ad-1e7a8d4ca630.jpg)
![img_4606](https://user-images.githubusercontent.com/47024076/52943886-6a0a7480-336e-11e9-9e94-4a9cd0234de2.jpg)

**Comment by gatoab** [comment] 2019-02-18 10:16
![img_4607](https://user-images.githubusercontent.com/47024076/52943975-aa69f280-336e-11e9-9520-2a9a122a1ceb.jpg)

**Comment by steve6375** [comment] 2019-02-18 10:20
What happens when you press ENTER after the last  ls (hd0,0) screen?

**Comment by gatoab** [comment] 2019-02-18 10:32
The system display:
pxe detected

No bootfile! pxe_blksize set to 512

and hang forever

**Comment by steve6375** [comment] 2019-02-18 10:34
Can you disable PXE (network) boot in the BIOS on the NAS?

**Comment by gatoab** [comment] 2019-02-18 10:46
No because:
step 1) boot PC via PXE on the NAS: grldr
step 2) menu.lst:
- map --top --mem (pd)/ipxe.iso (0xff)
- map --hook
- chainloader (0xff)
step 3) IPXE:
- dhcp net1
- set keep-san 1
- sanhook iscsi:192.168.1.10:::1:iqn:s.a
- sanboot
step e) here the system try to "load" the problematic grldr that is use to map a 10GB VHD

**Comment by steve6375** [comment] 2019-02-18 10:59
You did not say you were PXE booting!!!
You said you used grubinst to install boot code to hard disk - therefore I assumed you were booting from the hard disk.
So does the NAS boot OK if you boot from it's own internal hard disk?
It sounds like grub4dos PXE code cannot download the bootfile from your PXE server. Maybe you have not set up the PXE server correctly?
http://diddy.boot-land.net/grub4dos/files/pxe.htm

**Comment by steve6375** [comment] 2019-02-18 11:54
* map --top --mem (pd)/ipxe.iso (0xff)
Why is this using --top? Did you try without --top ?

**Comment by gatoab** [comment] 2019-02-18 13:28
> does the NAS boot OK if you boot from it's own internal hard disk? >> i dont want nor need to do/know that.
> 
Pxe server ok because step 1) is ok
Pxe server can load the IPXE stuff.
The sanboot command of the IPXE (not the pxe) stuff, with some grldr version, can load menu.lst. But via the sanboot, the grldr version that i need to use to map 10GB vhd  can not load the menu.lst . Thats the problem
To summerize
1)Ok: Boot via pxe to grldr menu.lst that map ipxe.iso then
2)Ko: ipxe sanboot to load grldr that should load menu.lst

All of this to boot a 10 gb vhd without real hard drive in the initial machine

**Comment by steve6375** [comment] 2019-02-18 13:48
OK, so after the sanboot command, the new grldr seems to be trying to pxe boot **again**,
Maybe the problem is that the older grldr did not have pxe detect in its default internal menu.lst or maybe the pxe boot file failed and it returned back to grub4dos but later versions do not return back to grub4dos?

Try modifying the internal menu in the \grldr file on the NAS that is loaded by sanboot so that instead of
`pxe detect`
it has 
`pxe unload`
because at that point, drive 0 should be the NAS drive so you don't need to pxe boot.

**Comment by gatoab** [comment] 2019-02-18 14:02
without --top, same "error"

**Comment by gatoab** [comment] 2019-02-18 14:03
result with pxe unload:
![img_4609](https://user-images.githubusercontent.com/47024076/52955915-32132980-338e-11e9-80c1-3c691225268f.jpg)

**Comment by gatoab** [comment] 2019-02-18 14:10
After your very good idea, I delete the PXE KEEP present in the "first" menu.lst and voilà: problem solved.
So thank you very very much for such a precious help!

**Comment by steve6375** [comment] 2019-02-18 14:17
Great! So you can close this issue as solved now?

**Closed as completed** 2019-02-18 14:17 UTC
